### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [reno99986/latihan_html#1]
### Halo Reno,

Jadi kodemu sudah terstruktur, akan tetap membutuhkan beberapa revisi seperti:

1. Header mungkin ditambah menjadi judul website dan navigasi:
```html
<header>
 <h1>...</h1>
 <nav>...</nav>
</header>
```

2. Didalam navigasi, kamu bisa menambahkan daftar untuk navigasi website. Sebagai contoh, didalam elemen `nav` kamu bisa menambah `ul` seperti:
```html
<nav>
 <ul>
  <li><a href="#section1">HTML</a></li>
 </ul>
 <a href="#html">HTML</a>
</nav>
```
lalu di elemen `section` pertama, bisa ditambahkan `id="section1"`
```html
<section id=html>...</article>
```
Jadi, elemen `a` yang kamu sudah tambahi tadi bisa menyambung ke section1. Ulangi langkah diatas untuk section lainnya.

3. Kamu tidak mengaplikasi elemen `<article>`. Kamu bisa menambah elemen `<section>` dengan isi elemen `<article>`. Bisa diikuti seperti dibawah:
```html
<section id="section4>
 <article>...</article>
</section>
```

4. elemen `form` kurang tepat penempatanya didalam `footer`. Kamu bisa membuat `section` baru seperti:
```html
<section id="section5">
 <form>...</form>
</section>
```

Jika sudah direvisi, harap komen dibawah yah dan upload ulang di repository yang sama. Semangat Revisi!

**Comment by reno99986** [comment]
Halo Kak, Terimakasih telah mereview tugas pembuatan HTML Saya, saya sudah mengupload ulang File HTML yang telah direvisi. Filenya mohon untuk direview ulang apabila berkenan

Terima Kasih

**Comment by not-xygen** [comment]
### Halo Reno,

dari aku sudah oke cuman ada beberapa yang perlu dibaiki seperti penggunann section tidak perlu berulang jika elemennya sama. Misal kamu membuat section `article`, kamu bisa mengabungkan beberapa elemen `article` pada satu `section`. Terlihat pada kodemu kamu masih memisah `article` per `section`. Bisa diubah lagi ya tapi overall udah oke jadi ku approve. 

Kuclose issue ini ya dan goodluck pada CSS nanti!
